# Generated by Django 3.1.4 on 2020-12-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageAge',
            fields=[
                ('avg_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='avg_a_id')),
                ('average_age', models.IntegerField(verbose_name='Average Age')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('avg_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='avg_r_id')),
                ('average_rating', models.IntegerField(verbose_name='Average Rating')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('clothing_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Clothing id')),
                ('age', models.CharField(max_length=120, verbose_name='Age')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('review', models.CharField(max_length=1024, verbose_name='Review')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('recommended', models.IntegerField(verbose_name='Recommended')),
                ('positive_feedback', models.IntegerField(verbose_name='Positive Feedback')),
                ('division', models.CharField(max_length=255, verbose_name='Division')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('class_name', models.CharField(max_length=120, verbose_name='Class name')),
            ],
        ),
    ]
