# Generated by Django 3.1.4 on 2020-12-29 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_counterrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterrow',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
